# Generated by Django 5.2.1 on 2025-08-12 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-booking_date',)},
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price_note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('solar', 'Solar Installation'), ('insulation', 'Home Insulation'), ('compost', 'Compost Pickup'), ('rainwater', 'Rainwater Harvesting')], db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('provider', 'booking_date'), name='uniq_provider_booking_date'),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='services.serviceprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together={('provider', 'date')},
        ),
    ]
