# Generated by Django 5.0.6 on 2025-08-12 17:24

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_provideravailability_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg']), services.models.validate_file_size]),
        ),
    ]
