# Generated by Django 5.0.6 on 2025-08-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_serviceprovider_options_and_more'),
    ]

    operations = [
    ]
